### ISSUE TITLE
Energy and Meter tag in Select statement

### ISSUE THREAD

**Issue by HelgeFH** [rebtor/nl.rebtor.sql#2]
Hi,

Documentation does not state the field names that is to be used in the select statement.

I use: "SELECT instant as power, '0' as meter FROM ..."
'power' is correct but i get no value for 'meter'. Suspect that it is has another name.

Please update the documentation

Thanks
Helge

**Comment by rebtor** [comment]
Field names for devices: 

Power device: power and meter
gas device: meter
weather device: temp and humidity

**Comment by Quart666** [comment]
I use this select statment but got nothing in the app but it retrives right when testing in mysql querybrowser, see picture
SELECT counts_a_60 AS 'power', counts_a_24 AS 'meter' FROM answers a ORDER BY Created DESC LIMIT 1;
![image](https://user-images.githubusercontent.com/41703868/57386293-5d026200-71b4-11e9-994a-913c14153f2d.png)

**Comment by rebtor** [comment]
Hi Quart666. 

What kind of device are you using? 

I use the power device with the following query: 

Select p1_current_power_in as power, p1_meterreading_in_1 +  p1_meterreading_in_2 as meter FROM Domotica.p1_log  order by p1_timestamp desc  limit 1

For the other devices you need to use the following fieldnames: 

Power device: power and meter
gas device: meter
weather device: temp and humidity
Sensor device: triggered (integer value greater then 0 is alarm triggered)

**Comment by Quart666** [comment]
Hi
Thanks for asking to this thread !!
I use Power device: power and meter. I now got it working. And I think it was something when entering query in the app on my Iphone. Because when I logon http://developer.athom.com/ and added the device there and copy/paste the query and other fields it starts working. So maybe some characters got wrong when writing it on my iphone.
